name: lando-heroku-sockets
recipe: mean
config:
  webroot: public
  node: 14
  build:
    - npm install
  command: npm start  
  port: 5000

services:
 appserver:
   extras:
    - "wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh"
   build_as_root:  
    - "wget https://github.com/tmedwards/tweego/releases/download/v2.1.1/tweego-2.1.1-linux-x64.zip -O temp.zip && unzip temp.zip -d /usr/local/bin && rm temp.zip && chmod a+x /usr/local/bin/tweego"
#    - "unzip temp.zip -d /usr/local/bin"
#    - "chmod a+x /usr/local/bin/tweego"

tooling:
  heroku:
    service: appserver
    cmd: /usr/bin/heroku